### ISSUE TITLE
Description of transparent cheating

### ISSUE THREAD

**Issue by ghost** [Dan-Q/hangman-cheat#1]
Brilliant game!

In the game settings, the description text of **transparent cheating** is the same as that for **cheat mode**, i.e.

> Transparent cheating
> Can the computer cheat by changing the word it has picked?

Instead, it would make sense to use the description from the README:

> Transparent cheating on: when the computer cheats, it'll tell you so. Turn this off to make the game feel like it's fair (but difficult).

**Comment by Dan-Q** [comment]
Fixed in 6a5058b154ce20e75cdc2e4bda83ea8e70b1cea5.
